name: Build Revanced APK
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  HAVE_TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID != '' }}
on:
  workflow_dispatch:
  repository_dispatch:
    event-type: Build Revanced APK

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build-apk:
    name: APK Build
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Update Env for custom build
        run: |
          echo "${{ secrets.ENVS }}" >> .env

      - name: Build Revanced APKs
        run: |
          docker-compose up

      - name: Get Date
        id: get-date
        run: |
          echo ::set-output name=date::$(TZ='Asia/Kolkata' date +"%Y.%m.%d-%H.%M.%S")

      - name: Upload Build Artifact
        uses: ncipollo/release-action@v1.11.1
        with:
          artifacts: "apks/*-output.apk,apks/VancedMicroG.apk"
          token: ${{ secrets.GH_TOKEN }}
          tag: Build-${{ steps.get-date.outputs.date }}
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
      - name: Sleep for 10 seconds
        run: |
          sleep 10

      - name: Upload to Telegram
        if: ${{ env.HAVE_TELEGRAM_API_ID == 'true' }}
        uses: nikhilbadyal/ghaction-telegram-uploader@main
        with:
          API_ID: ${{ secrets.TELEGRAM_API_ID }}
          API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
