name: Build Artifacts PR
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
on:
  workflow_call:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build-apk-pr:
    name: APK Build
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Update Env for custom build
        run: |
          echo "${{ secrets.ENVS }}" >> .env

      - name: Build Revanced APKs
        run: |
          docker-compose up

      - name: Get Date
        id: get-date
        run: |
          echo ::set-output name=date::$(TZ='Asia/Kolkata' date +"%Y.%m.%d-%H.%M.%S")

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build APKs
          path: |
            apks/*-output.apk
            apks/VancedMicroG.apk"
          if-no-files-found: error
